// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: platform/platform.proto

package platform

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHeightRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetHeightRequest) Reset() {
	*x = GetHeightRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_platform_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeightRequest) ProtoMessage() {}

func (x *GetHeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_platform_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeightRequest.ProtoReflect.Descriptor instead.
func (*GetHeightRequest) Descriptor() ([]byte, []int) {
	return file_platform_platform_proto_rawDescGZIP(), []int{0}
}

type GetHeightReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *GetHeightReply) Reset() {
	*x = GetHeightReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_platform_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHeightReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeightReply) ProtoMessage() {}

func (x *GetHeightReply) ProtoReflect() protoreflect.Message {
	mi := &file_platform_platform_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeightReply.ProtoReflect.Descriptor instead.
func (*GetHeightReply) Descriptor() ([]byte, []int) {
	return file_platform_platform_proto_rawDescGZIP(), []int{1}
}

func (x *GetHeightReply) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_platform_platform_proto protoreflect.FileDescriptor

var file_platform_platform_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x22, 0x12, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x28, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x48, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x32, 0x4d, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x41, 0x0a,
	0x09, 0x47, 0x65, 0x74, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1a, 0x2e, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61,
	0x76, 0x61, 0x2d, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x61, 0x76, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x68,
	0x65, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_platform_platform_proto_rawDescOnce sync.Once
	file_platform_platform_proto_rawDescData = file_platform_platform_proto_rawDesc
)

func file_platform_platform_proto_rawDescGZIP() []byte {
	file_platform_platform_proto_rawDescOnce.Do(func() {
		file_platform_platform_proto_rawDescData = protoimpl.X.CompressGZIP(file_platform_platform_proto_rawDescData)
	})
	return file_platform_platform_proto_rawDescData
}

var file_platform_platform_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_platform_platform_proto_goTypes = []interface{}{
	(*GetHeightRequest)(nil), // 0: platform.GetHeightRequest
	(*GetHeightReply)(nil),   // 1: platform.GetHeightReply
}
var file_platform_platform_proto_depIdxs = []int32{
	0, // 0: platform.Platform.GetHeight:input_type -> platform.GetHeightRequest
	1, // 1: platform.Platform.GetHeight:output_type -> platform.GetHeightReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_platform_platform_proto_init() }
func file_platform_platform_proto_init() {
	if File_platform_platform_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_platform_platform_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHeightRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_platform_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHeightReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_platform_platform_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_platform_platform_proto_goTypes,
		DependencyIndexes: file_platform_platform_proto_depIdxs,
		MessageInfos:      file_platform_platform_proto_msgTypes,
	}.Build()
	File_platform_platform_proto = out.File
	file_platform_platform_proto_rawDesc = nil
	file_platform_platform_proto_goTypes = nil
	file_platform_platform_proto_depIdxs = nil
}
